language: scala
jdk: openjdk11

matrix:
  include:
    - scala: 2.13.1
      env: PLATFORM="jvm"
      script: sbt "++2.13.1" coverage core/test bench/compile docs/mdoc coverageReport && codecov

    - scala: 2.12.9
      env: PLATFORM="jvm"
      script: sbt "++2.12.9" coverage core/test bench/compile docs/mdoc coverageReport && codecov

    - scala: 2.11.12
      env: PLATFORM="jvm"
      script: sbt "++2.11.12" coverage core/test bench/compile docs/mdoc coverageReport && codecov

install:
 - pip install --user codecov

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier
  - $HOME/.nvm

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
